from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ROOT.parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from stock_analysis.reports.report_generator import (
    generate_reports_from_candidates,
    load_candidates_json,
    load_frame_json,
    load_summary_json,
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Phase 1 Markdown/HTML research reports from candidates.")
    parser.add_argument("--candidates", required=True, help="Path to candidates JSON generated by run_daily_research.py.")
    parser.add_argument("--summary", default=None, help="Optional JSON summary file.")
    parser.add_argument("--factors", default=None, help="Optional factors JSON generated by run_daily_research.py.")
    parser.add_argument("--factor-explanations", default=None, help="Optional factor explanations JSON generated by run_daily_research.py.")
    parser.add_argument("--output-dir", default=str(REPO_ROOT / "outputs" / "reports"))
    parser.add_argument("--updated-at", default=None)
    args = parser.parse_args()

    candidates = load_candidates_json(args.candidates)
    input_warnings: list[str] = []
    summary = _load_optional_summary(args.summary, input_warnings)
    factors = _load_optional_frame(args.factors, "factors", input_warnings)
    explanations = _load_optional_frame(args.factor_explanations, "factor_explanations", input_warnings)
    artifacts = generate_reports_from_candidates(
        candidates,
        summary=summary,
        factors=factors,
        explanations=explanations,
        output_dir=args.output_dir,
        updated_at=args.updated_at,
        input_warnings=input_warnings,
    )
    payload = {
        "status": "ok",
        "candidates": str(Path(args.candidates).resolve()),
        "output_dir": str(Path(args.output_dir).resolve()),
        **artifacts,
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def _load_summary(path: str | None) -> dict[str, object]:
    return _load_optional_summary(path, [])


def _load_optional_summary(path: str | None, warnings: list[str]) -> dict[str, object]:
    if not path:
        warnings.append("missing_summary_input: daily report summary uses available candidate fields only.")
        return {}
    summary_path = Path(path)
    if not summary_path.exists():
        warnings.append(f"missing_summary_file: {summary_path}")
        return {}
    return load_summary_json(summary_path)


def _load_optional_frame(path: str | None, name: str, warnings: list[str]):
    if not path:
        warnings.append(f"missing_{name}_input")
        return None
    frame_path = Path(path)
    if not frame_path.exists():
        warnings.append(f"missing_{name}_file: {frame_path}")
        return None
    return load_frame_json(frame_path)


if __name__ == "__main__":
    raise SystemExit(main())
