from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ROOT.parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from stock_analysis.reports.report_generator import generate_reports_from_candidates, load_candidates_json


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Phase 1 Markdown/HTML research reports from candidates.")
    parser.add_argument("--candidates", required=True, help="Path to candidates JSON generated by run_daily_research.py.")
    parser.add_argument("--summary", default=None, help="Optional JSON summary file.")
    parser.add_argument("--output-dir", default=str(REPO_ROOT / "outputs" / "reports"))
    parser.add_argument("--updated-at", default=None)
    args = parser.parse_args()

    candidates = load_candidates_json(args.candidates)
    summary = _load_summary(args.summary)
    artifacts = generate_reports_from_candidates(
        candidates,
        summary=summary,
        output_dir=args.output_dir,
        updated_at=args.updated_at,
    )
    payload = {
        "status": "ok",
        "candidates": str(Path(args.candidates).resolve()),
        "output_dir": str(Path(args.output_dir).resolve()),
        **artifacts,
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def _load_summary(path: str | None) -> dict[str, object]:
    if not path:
        return {}
    payload = json.loads(Path(path).read_text(encoding="utf-8-sig"))
    if isinstance(payload, dict) and "summary" in payload and isinstance(payload["summary"], dict):
        return payload["summary"]
    if isinstance(payload, dict):
        return payload
    raise ValueError("Summary JSON must contain an object.")


if __name__ == "__main__":
    raise SystemExit(main())
